name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: npm install, build, and test
        run: |
          npm ci
          npm run bootstrap
          npm run lint 
          npm run migrate:test
          npm run test:ci
        env:
          CI: true
#     - uses: codecov/codecov-action@v1
#       with:
#         name: jest
#         token: ${{ secrets.CODECOV_TOKEN }}
#         file: ./coverage/coverage-final.json
